# Generated by Django 3.2.18 on 2023-04-29 03:45

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0003_auto_20230302_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositswithdrawalsstats',
            name='stats',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AlterField(
            model_name='gaskeeper',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='keeper',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transactioninputscore',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
