# Generated by Django 3.2.18 on 2023-04-29 03:45

from django.db import migrations, models
import sci.mercado_pago


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230413_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coininfo',
            name='tx_explorer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paygatetopup',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='paygatetopup',
            name='gate_id',
            field=models.IntegerField(choices=[('1', sci.mercado_pago.MercadoPago)]),
        ),
        migrations.AlterField(
            model_name='sourceoffunds',
            name='is_beneficiary',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='internal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='kyc_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
