# Generated by Django 3.2.18 on 2023-04-29 21:07

import core.currency
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def create_mxn_wallets(apps, schema_editor):
    UserFiatWallet = apps.get_model('core', 'UserFiatWallet')

    wallets = UserFiatWallet.objects.filter()
    count = wallets.count()

    print(f'MXN Wallets generation started. Total: {count}')
    
    for wallet in wallets:
        UserFiatWallet.objects.create(
            user_id=wallet.user_id,
            currency='MXN',
        )
        wallet.is_old = True
        wallet.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_auto_20230429_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFiatWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('currency', core.currency.CurrencyModelField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('amount_in_orders', models.DecimalField(decimal_places=5, default=0, max_digits=30)),
                ('merchant', models.BooleanField(default=True)),
                ('block_type', models.SmallIntegerField(choices=[(0, 'Not blocked'), (1, 'Deposits'), (2, 'Deposits + Accumulations')], default=0)),
                ('is_old', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'currency')},
            },
        ),
        migrations.RunPython(create_mxn_wallets),
    ]
